/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_blank_line = 1,
  sym_comment = 2,
  anon_sym_AT = 3,
  aux_sym_variable_declaration_token1 = 4,
  anon_sym_EQ = 5,
  anon_sym_LF = 6,
  sym_identifier = 7,
  sym_variable_value = 8,
  sym_request_separator = 9,
  aux_sym_request_name_token1 = 10,
  aux_sym_request_line_token1 = 11,
  anon_sym_GET = 12,
  anon_sym_POST = 13,
  anon_sym_PUT = 14,
  anon_sym_PATCH = 15,
  anon_sym_DELETE = 16,
  anon_sym_HEAD = 17,
  anon_sym_OPTIONS = 18,
  anon_sym_GRAPHQL = 19,
  aux_sym_url_token1 = 20,
  sym_interpolation = 21,
  anon_sym_COLON = 22,
  sym_header_name = 23,
  sym_json_string = 24,
  sym_json_number = 25,
  sym_source_file = 26,
  sym_variable_declaration = 27,
  sym_request = 28,
  sym_request_name = 29,
  sym_request_line = 30,
  sym_method = 31,
  sym_url = 32,
  sym_header = 33,
  sym_header_value = 34,
  sym_body = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_request_repeat1 = 37,
  aux_sym_request_repeat2 = 38,
  aux_sym_url_repeat1 = 39,
  aux_sym_header_value_repeat1 = 40,
  aux_sym_body_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [anon_sym_AT] = "@",
  [aux_sym_variable_declaration_token1] = "variable_declaration_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_LF] = "\n",
  [sym_identifier] = "identifier",
  [sym_variable_value] = "variable_value",
  [sym_request_separator] = "request_separator",
  [aux_sym_request_name_token1] = "request_name_token1",
  [aux_sym_request_line_token1] = "request_line_token1",
  [anon_sym_GET] = "GET",
  [anon_sym_POST] = "POST",
  [anon_sym_PUT] = "PUT",
  [anon_sym_PATCH] = "PATCH",
  [anon_sym_DELETE] = "DELETE",
  [anon_sym_HEAD] = "HEAD",
  [anon_sym_OPTIONS] = "OPTIONS",
  [anon_sym_GRAPHQL] = "GRAPHQL",
  [aux_sym_url_token1] = "url_token1",
  [sym_interpolation] = "interpolation",
  [anon_sym_COLON] = ":",
  [sym_header_name] = "header_name",
  [sym_json_string] = "json_string",
  [sym_json_number] = "json_number",
  [sym_source_file] = "source_file",
  [sym_variable_declaration] = "variable_declaration",
  [sym_request] = "request",
  [sym_request_name] = "request_name",
  [sym_request_line] = "request_line",
  [sym_method] = "method",
  [sym_url] = "url",
  [sym_header] = "header",
  [sym_header_value] = "header_value",
  [sym_body] = "body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_request_repeat1] = "request_repeat1",
  [aux_sym_request_repeat2] = "request_repeat2",
  [aux_sym_url_repeat1] = "url_repeat1",
  [aux_sym_header_value_repeat1] = "header_value_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_variable_declaration_token1] = aux_sym_variable_declaration_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LF] = anon_sym_LF,
  [sym_identifier] = sym_identifier,
  [sym_variable_value] = sym_variable_value,
  [sym_request_separator] = sym_request_separator,
  [aux_sym_request_name_token1] = aux_sym_request_name_token1,
  [aux_sym_request_line_token1] = aux_sym_request_line_token1,
  [anon_sym_GET] = anon_sym_GET,
  [anon_sym_POST] = anon_sym_POST,
  [anon_sym_PUT] = anon_sym_PUT,
  [anon_sym_PATCH] = anon_sym_PATCH,
  [anon_sym_DELETE] = anon_sym_DELETE,
  [anon_sym_HEAD] = anon_sym_HEAD,
  [anon_sym_OPTIONS] = anon_sym_OPTIONS,
  [anon_sym_GRAPHQL] = anon_sym_GRAPHQL,
  [aux_sym_url_token1] = aux_sym_url_token1,
  [sym_interpolation] = sym_interpolation,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name] = sym_header_name,
  [sym_json_string] = sym_json_string,
  [sym_json_number] = sym_json_number,
  [sym_source_file] = sym_source_file,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_request] = sym_request,
  [sym_request_name] = sym_request_name,
  [sym_request_line] = sym_request_line,
  [sym_method] = sym_method,
  [sym_url] = sym_url,
  [sym_header] = sym_header,
  [sym_header_value] = sym_header_value,
  [sym_body] = sym_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_request_repeat1] = aux_sym_request_repeat1,
  [aux_sym_request_repeat2] = aux_sym_request_repeat2,
  [aux_sym_url_repeat1] = aux_sym_url_repeat1,
  [aux_sym_header_value_repeat1] = aux_sym_header_value_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_variable_declaration_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_value] = {
    .visible = true,
    .named = true,
  },
  [sym_request_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_request_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DELETE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HEAD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OPTIONS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GRAPHQL] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_url_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_json_string] = {
    .visible = true,
    .named = true,
  },
  [sym_json_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_request] = {
    .visible = true,
    .named = true,
  },
  [sym_request_name] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_url_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_method = 2,
  field_name = 3,
  field_url = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_method] = "method",
  [field_name] = "name",
  [field_url] = "url",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 2},
  [11] = {.index = 17, .length = 1},
  [12] = {.index = 18, .length = 2},
  [13] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_value, 3},
  [2] =
    {field_method, 0},
    {field_url, 2},
  [4] =
    {field_name, 1},
  [5] =
    {field_name, 1},
    {field_value, 4},
  [7] =
    {field_body, 5},
  [8] =
    {field_name, 1},
    {field_value, 5},
  [10] =
    {field_name, 0},
    {field_value, 2},
  [12] =
    {field_body, 6},
  [13] =
    {field_body, 6},
    {field_name, 1},
  [15] =
    {field_name, 0},
    {field_value, 3},
  [17] =
    {field_body, 7},
  [18] =
    {field_body, 7},
    {field_name, 1},
  [20] =
    {field_body, 8},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '-') ADVANCE(133);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ':') ADVANCE(131);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '@') ADVANCE(49);
      if (lookahead == 'D') ADVANCE(64);
      if (lookahead == 'G') ADVANCE(65);
      if (lookahead == 'H') ADVANCE(67);
      if (lookahead == 'O') ADVANCE(77);
      if (lookahead == 'P') ADVANCE(61);
      if (lookahead == '_') ADVANCE(88);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '#') ADVANCE(48);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'D') ADVANCE(12);
      if (lookahead == 'G') ADVANCE(13);
      if (lookahead == 'H') ADVANCE(15);
      if (lookahead == 'O') ADVANCE(25);
      if (lookahead == 'P') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(108);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(95);
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '-') ADVANCE(104);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(96);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') SKIP(4);
      if (lookahead == '{') ADVANCE(125);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(108);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(129);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(135);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(48);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(31);
      if (lookahead == 'O') ADVANCE(28);
      if (lookahead == 'U') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(119);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == 'R') ADVANCE(8);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(117);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'H') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'H') ADVANCE(115);
      END_STATE();
    case 19:
      if (lookahead == 'I') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'L') ADVANCE(123);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'N') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'P') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'P') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'Q') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 'S') ADVANCE(121);
      END_STATE();
    case 28:
      if (lookahead == 'S') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'T') ADVANCE(109);
      END_STATE();
    case 30:
      if (lookahead == 'T') ADVANCE(19);
      END_STATE();
    case 31:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 'T') ADVANCE(113);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(111);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 35:
      if (lookahead == '{') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == '}') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      if (lookahead == '}') ADVANCE(130);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 39:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 40:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 41:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '\n', 58,
        '\r', 94,
        '"', 93,
        '#', 47,
        '-', 104,
        '/', 98,
        '@', 50,
        '{', 99,
        '\t', 103,
        ' ', 103,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 42:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == '\r') SKIP(42);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '@') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(108);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') SKIP(43);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '@') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(108);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\r') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\r') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(45);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(63);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(76);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(83);
      if (lookahead == 'O') ADVANCE(80);
      if (lookahead == 'U') ADVANCE(84);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'C') ADVANCE(70);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(120);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(73);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(81);
      if (lookahead == 'R') ADVANCE(60);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(118);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(59);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(86);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H') ADVANCE(78);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H') ADVANCE(116);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I') ADVANCE(75);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(124);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(68);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N') ADVANCE(79);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(74);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(69);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(82);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Q') ADVANCE(72);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(122);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(85);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(110);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(71);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(62);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(114);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(112);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(66);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_variable_value);
      if (lookahead == '\r') ADVANCE(89);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_variable_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_variable_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_request_separator);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '"') ADVANCE(107);
      if (lookahead == '\\') ADVANCE(106);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      ADVANCE_MAP(
        '\r', 94,
        '"', 93,
        '#', 47,
        '-', 104,
        '/', 98,
        '@', 50,
        '{', 99,
        '\t', 103,
        ' ', 103,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '\r') ADVANCE(95);
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '-') ADVANCE(104);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '\r') ADVANCE(96);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '.') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '{') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '}') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '}') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '}') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_request_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_GET);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_GET);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_POST);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_POST);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_PUT);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_PUT);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_PATCH);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_PATCH);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_DELETE);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_DELETE);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_HEAD);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_HEAD);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_GRAPHQL);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_GRAPHQL);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '{') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(129);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '}') ADVANCE(129);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(128);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '}') ADVANCE(129);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(129);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '}') ADVANCE(127);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_interpolation);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '.') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_header_name);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_json_string);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_json_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 43},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 41},
  [7] = {.lex_state = 41},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 42},
  [10] = {.lex_state = 42},
  [11] = {.lex_state = 42},
  [12] = {.lex_state = 42},
  [13] = {.lex_state = 42},
  [14] = {.lex_state = 42},
  [15] = {.lex_state = 42},
  [16] = {.lex_state = 42},
  [17] = {.lex_state = 42},
  [18] = {.lex_state = 43},
  [19] = {.lex_state = 43},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 42},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 43},
  [28] = {.lex_state = 43},
  [29] = {.lex_state = 43},
  [30] = {.lex_state = 51},
  [31] = {.lex_state = 43},
  [32] = {.lex_state = 43},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 43},
  [35] = {.lex_state = 43},
  [36] = {.lex_state = 43},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 54},
  [45] = {.lex_state = 52},
  [46] = {.lex_state = 52},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 43},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 89},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 89},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_request_separator] = ACTIONS(1),
    [aux_sym_request_line_token1] = ACTIONS(3),
    [anon_sym_GET] = ACTIONS(1),
    [anon_sym_POST] = ACTIONS(1),
    [anon_sym_PUT] = ACTIONS(1),
    [anon_sym_PATCH] = ACTIONS(1),
    [anon_sym_DELETE] = ACTIONS(1),
    [anon_sym_HEAD] = ACTIONS(1),
    [anon_sym_OPTIONS] = ACTIONS(1),
    [anon_sym_GRAPHQL] = ACTIONS(1),
    [sym_interpolation] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
    [sym_json_string] = ACTIONS(1),
    [sym_json_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(57),
    [sym_variable_declaration] = STATE(19),
    [sym_request] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_blank_line] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [sym_request_separator] = ACTIONS(13),
    [aux_sym_request_line_token1] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(3), 1,
      aux_sym_request_repeat1,
    STATE(65), 1,
      sym_request_line,
    STATE(66), 1,
      sym_method,
    ACTIONS(15), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [27] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(8), 1,
      aux_sym_request_repeat1,
    STATE(53), 1,
      sym_request_line,
    STATE(66), 1,
      sym_method,
    ACTIONS(19), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [54] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(5), 1,
      aux_sym_request_repeat1,
    STATE(54), 1,
      sym_request_line,
    STATE(66), 1,
      sym_method,
    ACTIONS(21), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [81] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(8), 1,
      aux_sym_request_repeat1,
    STATE(47), 1,
      sym_request_line,
    STATE(66), 1,
      sym_method,
    ACTIONS(19), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [108] = 5,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    STATE(7), 1,
      aux_sym_body_repeat1,
    ACTIONS(25), 4,
      sym_blank_line,
      sym_comment,
      anon_sym_AT,
      sym_request_separator,
    ACTIONS(27), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [131] = 5,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_body_repeat1,
    ACTIONS(33), 4,
      sym_blank_line,
      sym_comment,
      anon_sym_AT,
      sym_request_separator,
    ACTIONS(35), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [154] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(8), 1,
      aux_sym_request_repeat1,
    ACTIONS(38), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(41), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [175] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(47), 1,
      anon_sym_LF,
    ACTIONS(49), 1,
      sym_header_name,
    STATE(13), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(45), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [200] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(49), 1,
      sym_header_name,
    ACTIONS(55), 1,
      anon_sym_LF,
    STATE(16), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(53), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [225] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(49), 1,
      sym_header_name,
    ACTIONS(61), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(59), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [250] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(47), 1,
      anon_sym_LF,
    ACTIONS(49), 1,
      sym_header_name,
    STATE(14), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(45), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [275] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(67), 1,
      sym_header_name,
    STATE(13), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(65), 4,
      sym_blank_line,
      sym_comment,
      anon_sym_LF,
      sym_request_separator,
  [298] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(49), 1,
      sym_header_name,
    ACTIONS(74), 1,
      anon_sym_LF,
    STATE(13), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(72), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [323] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(49), 1,
      sym_header_name,
    ACTIONS(80), 1,
      anon_sym_LF,
    STATE(17), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(78), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [348] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(49), 1,
      sym_header_name,
    ACTIONS(80), 1,
      anon_sym_LF,
    STATE(13), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(78), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [373] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(49), 1,
      sym_header_name,
    ACTIONS(86), 1,
      anon_sym_LF,
    STATE(13), 1,
      aux_sym_request_repeat2,
    STATE(62), 1,
      sym_header,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
    ACTIONS(84), 3,
      sym_blank_line,
      sym_comment,
      sym_request_separator,
  [398] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      sym_blank_line,
    ACTIONS(93), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_AT,
    ACTIONS(99), 1,
      sym_request_separator,
    STATE(18), 3,
      sym_variable_declaration,
      sym_request,
      aux_sym_source_file_repeat1,
  [422] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_request_separator,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      sym_blank_line,
    ACTIONS(106), 1,
      sym_comment,
    STATE(18), 3,
      sym_variable_declaration,
      sym_request,
      aux_sym_source_file_repeat1,
  [446] = 4,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_body_repeat1,
    STATE(29), 1,
      sym_body,
    ACTIONS(108), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [463] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_header_name,
    ACTIONS(65), 4,
      sym_blank_line,
      sym_comment,
      anon_sym_LF,
      sym_request_separator,
  [478] = 4,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_body_repeat1,
    STATE(32), 1,
      sym_body,
    ACTIONS(108), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [495] = 4,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_body_repeat1,
    STATE(35), 1,
      sym_body,
    ACTIONS(108), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [512] = 4,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_body_repeat1,
    STATE(34), 1,
      sym_body,
    ACTIONS(108), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [529] = 4,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_body_repeat1,
    STATE(33), 1,
      sym_body,
    ACTIONS(108), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [546] = 4,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_body_repeat1,
    STATE(36), 1,
      sym_body,
    ACTIONS(108), 5,
      anon_sym_LF,
      aux_sym_request_name_token1,
      sym_interpolation,
      sym_json_string,
      sym_json_number,
  [563] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(112), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [576] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(116), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [589] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(120), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [602] = 5,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(122), 1,
      aux_sym_variable_declaration_token1,
    STATE(42), 1,
      aux_sym_header_value_repeat1,
    STATE(56), 1,
      sym_header_value,
    ACTIONS(124), 2,
      aux_sym_request_name_token1,
      sym_interpolation,
  [619] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(128), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [632] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(132), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [645] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(136), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [658] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(140), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(138), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [671] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(144), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [684] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(148), 2,
      sym_comment,
      sym_request_separator,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
  [697] = 5,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(150), 1,
      anon_sym_LF,
    ACTIONS(152), 1,
      aux_sym_request_name_token1,
    ACTIONS(155), 1,
      sym_interpolation,
    STATE(37), 1,
      aux_sym_header_value_repeat1,
  [713] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(40), 1,
      aux_sym_url_repeat1,
    STATE(63), 1,
      sym_url,
    ACTIONS(158), 2,
      aux_sym_url_token1,
      sym_interpolation,
  [727] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(160), 1,
      anon_sym_LF,
    STATE(39), 1,
      aux_sym_url_repeat1,
    ACTIONS(162), 2,
      aux_sym_url_token1,
      sym_interpolation,
  [741] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(165), 1,
      anon_sym_LF,
    STATE(39), 1,
      aux_sym_url_repeat1,
    ACTIONS(167), 2,
      aux_sym_url_token1,
      sym_interpolation,
  [755] = 5,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(124), 1,
      sym_interpolation,
    ACTIONS(169), 1,
      aux_sym_request_name_token1,
    STATE(42), 1,
      aux_sym_header_value_repeat1,
    STATE(61), 1,
      sym_header_value,
  [771] = 5,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(171), 1,
      anon_sym_LF,
    ACTIONS(173), 1,
      aux_sym_request_name_token1,
    ACTIONS(175), 1,
      sym_interpolation,
    STATE(37), 1,
      aux_sym_header_value_repeat1,
  [787] = 4,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(177), 1,
      anon_sym_LF,
    ACTIONS(179), 1,
      aux_sym_request_name_token1,
    STATE(55), 1,
      sym_request_name,
  [800] = 3,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(181), 1,
      aux_sym_variable_declaration_token1,
    ACTIONS(183), 1,
      anon_sym_EQ,
  [810] = 3,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(185), 1,
      aux_sym_variable_declaration_token1,
    ACTIONS(187), 1,
      sym_variable_value,
  [820] = 3,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(189), 1,
      aux_sym_variable_declaration_token1,
    ACTIONS(191), 1,
      sym_variable_value,
  [830] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(193), 1,
      anon_sym_LF,
  [837] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(195), 1,
      sym_identifier,
  [844] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(197), 1,
      anon_sym_LF,
  [851] = 2,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(199), 1,
      sym_variable_value,
  [858] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(201), 1,
      anon_sym_LF,
  [865] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(203), 1,
      anon_sym_LF,
  [872] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(205), 1,
      anon_sym_LF,
  [879] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(207), 1,
      anon_sym_LF,
  [886] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(209), 1,
      anon_sym_LF,
  [893] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(211), 1,
      anon_sym_LF,
  [900] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [907] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(215), 1,
      anon_sym_EQ,
  [914] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(217), 1,
      anon_sym_LF,
  [921] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(219), 1,
      anon_sym_COLON,
  [928] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(221), 1,
      anon_sym_LF,
  [935] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(223), 1,
      anon_sym_LF,
  [942] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(225), 1,
      anon_sym_LF,
  [949] = 2,
    ACTIONS(29), 1,
      aux_sym_request_line_token1,
    ACTIONS(227), 1,
      sym_variable_value,
  [956] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(229), 1,
      anon_sym_LF,
  [963] = 1,
    ACTIONS(231), 1,
      aux_sym_request_line_token1,
  [967] = 1,
    ACTIONS(233), 1,
      aux_sym_request_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 131,
  [SMALL_STATE(8)] = 154,
  [SMALL_STATE(9)] = 175,
  [SMALL_STATE(10)] = 200,
  [SMALL_STATE(11)] = 225,
  [SMALL_STATE(12)] = 250,
  [SMALL_STATE(13)] = 275,
  [SMALL_STATE(14)] = 298,
  [SMALL_STATE(15)] = 323,
  [SMALL_STATE(16)] = 348,
  [SMALL_STATE(17)] = 373,
  [SMALL_STATE(18)] = 398,
  [SMALL_STATE(19)] = 422,
  [SMALL_STATE(20)] = 446,
  [SMALL_STATE(21)] = 463,
  [SMALL_STATE(22)] = 478,
  [SMALL_STATE(23)] = 495,
  [SMALL_STATE(24)] = 512,
  [SMALL_STATE(25)] = 529,
  [SMALL_STATE(26)] = 546,
  [SMALL_STATE(27)] = 563,
  [SMALL_STATE(28)] = 576,
  [SMALL_STATE(29)] = 589,
  [SMALL_STATE(30)] = 602,
  [SMALL_STATE(31)] = 619,
  [SMALL_STATE(32)] = 632,
  [SMALL_STATE(33)] = 645,
  [SMALL_STATE(34)] = 658,
  [SMALL_STATE(35)] = 671,
  [SMALL_STATE(36)] = 684,
  [SMALL_STATE(37)] = 697,
  [SMALL_STATE(38)] = 713,
  [SMALL_STATE(39)] = 727,
  [SMALL_STATE(40)] = 741,
  [SMALL_STATE(41)] = 755,
  [SMALL_STATE(42)] = 771,
  [SMALL_STATE(43)] = 787,
  [SMALL_STATE(44)] = 800,
  [SMALL_STATE(45)] = 810,
  [SMALL_STATE(46)] = 820,
  [SMALL_STATE(47)] = 830,
  [SMALL_STATE(48)] = 837,
  [SMALL_STATE(49)] = 844,
  [SMALL_STATE(50)] = 851,
  [SMALL_STATE(51)] = 858,
  [SMALL_STATE(52)] = 865,
  [SMALL_STATE(53)] = 872,
  [SMALL_STATE(54)] = 879,
  [SMALL_STATE(55)] = 886,
  [SMALL_STATE(56)] = 893,
  [SMALL_STATE(57)] = 900,
  [SMALL_STATE(58)] = 907,
  [SMALL_STATE(59)] = 914,
  [SMALL_STATE(60)] = 921,
  [SMALL_STATE(61)] = 928,
  [SMALL_STATE(62)] = 935,
  [SMALL_STATE(63)] = 942,
  [SMALL_STATE(64)] = 949,
  [SMALL_STATE(65)] = 956,
  [SMALL_STATE(66)] = 963,
  [SMALL_STATE(67)] = 967,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_request_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_request_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 5, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 5, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 5, 0, 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 5, 0, 3),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_request_repeat2, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_request_repeat2, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_request_repeat2, 2, 0, 0), SHIFT_REPEAT(60),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 6, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 6, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 6, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 6, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 7, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 7, 0, 3),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 6, 0, 4),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 6, 0, 4),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 6, 0, 5),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 6, 0, 5),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 7, 0, 6),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 7, 0, 6),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 7, 0, 8),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 7, 0, 8),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 7, 0, 9),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 7, 0, 9),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 8, 0, 11),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 8, 0, 11),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 8, 0, 12),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 8, 0, 12),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 9, 0, 13),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 9, 0, 13),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_value, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_name, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 7),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 10),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 3, 0, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_http_request(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
