/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_blank_line = 1,
  sym_comment = 2,
  anon_sym_AT = 3,
  aux_sym_variable_declaration_token1 = 4,
  anon_sym_EQ = 5,
  anon_sym_LF = 6,
  sym_identifier = 7,
  sym_variable_value = 8,
  sym_request_separator = 9,
  aux_sym_request_name_token1 = 10,
  aux_sym_request_line_token1 = 11,
  anon_sym_GET = 12,
  anon_sym_POST = 13,
  anon_sym_PUT = 14,
  anon_sym_PATCH = 15,
  anon_sym_DELETE = 16,
  anon_sym_HEAD = 17,
  anon_sym_OPTIONS = 18,
  anon_sym_GRAPHQL = 19,
  aux_sym_url_token1 = 20,
  sym_interpolation = 21,
  anon_sym_COLON = 22,
  sym_header_name = 23,
  sym_body = 24,
  sym_source_file = 25,
  sym_variable_declaration = 26,
  sym_request = 27,
  sym_request_name = 28,
  sym_request_line = 29,
  sym_method = 30,
  sym_url = 31,
  sym_header = 32,
  sym_header_value = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_request_repeat1 = 35,
  aux_sym_request_repeat2 = 36,
  aux_sym_url_repeat1 = 37,
  aux_sym_header_value_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [anon_sym_AT] = "@",
  [aux_sym_variable_declaration_token1] = "variable_declaration_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_LF] = "\n",
  [sym_identifier] = "identifier",
  [sym_variable_value] = "variable_value",
  [sym_request_separator] = "request_separator",
  [aux_sym_request_name_token1] = "request_name_token1",
  [aux_sym_request_line_token1] = "request_line_token1",
  [anon_sym_GET] = "GET",
  [anon_sym_POST] = "POST",
  [anon_sym_PUT] = "PUT",
  [anon_sym_PATCH] = "PATCH",
  [anon_sym_DELETE] = "DELETE",
  [anon_sym_HEAD] = "HEAD",
  [anon_sym_OPTIONS] = "OPTIONS",
  [anon_sym_GRAPHQL] = "GRAPHQL",
  [aux_sym_url_token1] = "url_token1",
  [sym_interpolation] = "interpolation",
  [anon_sym_COLON] = ":",
  [sym_header_name] = "header_name",
  [sym_body] = "body",
  [sym_source_file] = "source_file",
  [sym_variable_declaration] = "variable_declaration",
  [sym_request] = "request",
  [sym_request_name] = "request_name",
  [sym_request_line] = "request_line",
  [sym_method] = "method",
  [sym_url] = "url",
  [sym_header] = "header",
  [sym_header_value] = "header_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_request_repeat1] = "request_repeat1",
  [aux_sym_request_repeat2] = "request_repeat2",
  [aux_sym_url_repeat1] = "url_repeat1",
  [aux_sym_header_value_repeat1] = "header_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_variable_declaration_token1] = aux_sym_variable_declaration_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LF] = anon_sym_LF,
  [sym_identifier] = sym_identifier,
  [sym_variable_value] = sym_variable_value,
  [sym_request_separator] = sym_request_separator,
  [aux_sym_request_name_token1] = aux_sym_request_name_token1,
  [aux_sym_request_line_token1] = aux_sym_request_line_token1,
  [anon_sym_GET] = anon_sym_GET,
  [anon_sym_POST] = anon_sym_POST,
  [anon_sym_PUT] = anon_sym_PUT,
  [anon_sym_PATCH] = anon_sym_PATCH,
  [anon_sym_DELETE] = anon_sym_DELETE,
  [anon_sym_HEAD] = anon_sym_HEAD,
  [anon_sym_OPTIONS] = anon_sym_OPTIONS,
  [anon_sym_GRAPHQL] = anon_sym_GRAPHQL,
  [aux_sym_url_token1] = aux_sym_url_token1,
  [sym_interpolation] = sym_interpolation,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name] = sym_header_name,
  [sym_body] = sym_body,
  [sym_source_file] = sym_source_file,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_request] = sym_request,
  [sym_request_name] = sym_request_name,
  [sym_request_line] = sym_request_line,
  [sym_method] = sym_method,
  [sym_url] = sym_url,
  [sym_header] = sym_header,
  [sym_header_value] = sym_header_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_request_repeat1] = aux_sym_request_repeat1,
  [aux_sym_request_repeat2] = aux_sym_request_repeat2,
  [aux_sym_url_repeat1] = aux_sym_url_repeat1,
  [aux_sym_header_value_repeat1] = aux_sym_header_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_variable_declaration_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_value] = {
    .visible = true,
    .named = true,
  },
  [sym_request_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_request_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DELETE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HEAD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OPTIONS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GRAPHQL] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_url_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_request] = {
    .visible = true,
    .named = true,
  },
  [sym_request_name] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_url_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_method = 2,
  field_name = 3,
  field_url = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_method] = "method",
  [field_name] = "name",
  [field_url] = "url",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 2},
  [11] = {.index = 17, .length = 1},
  [12] = {.index = 18, .length = 2},
  [13] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_value, 3},
  [2] =
    {field_method, 0},
    {field_url, 2},
  [4] =
    {field_name, 1},
  [5] =
    {field_name, 1},
    {field_value, 4},
  [7] =
    {field_body, 5},
  [8] =
    {field_name, 1},
    {field_value, 5},
  [10] =
    {field_name, 0},
    {field_value, 2},
  [12] =
    {field_body, 6},
  [13] =
    {field_body, 6},
    {field_name, 1},
  [15] =
    {field_name, 0},
    {field_value, 3},
  [17] =
    {field_body, 7},
  [18] =
    {field_body, 7},
    {field_name, 1},
  [20] =
    {field_body, 8},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ':') ADVANCE(123);
      if (lookahead == '=') ADVANCE(55);
      if (lookahead == '@') ADVANCE(49);
      if (lookahead == 'D') ADVANCE(63);
      if (lookahead == 'G') ADVANCE(64);
      if (lookahead == 'H') ADVANCE(66);
      if (lookahead == 'O') ADVANCE(76);
      if (lookahead == 'P') ADVANCE(60);
      if (lookahead == '_') ADVANCE(87);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(43);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'D') ADVANCE(12);
      if (lookahead == 'G') ADVANCE(13);
      if (lookahead == 'H') ADVANCE(15);
      if (lookahead == 'O') ADVANCE(25);
      if (lookahead == 'P') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') SKIP(2);
      if (lookahead == '{') ADVANCE(117);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(121);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '{') ADVANCE(93);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(97);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == '\r') ADVANCE(125);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(127);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(48);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(31);
      if (lookahead == 'O') ADVANCE(28);
      if (lookahead == 'U') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(111);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == 'R') ADVANCE(8);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(109);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'H') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'H') ADVANCE(107);
      END_STATE();
    case 19:
      if (lookahead == 'I') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'L') ADVANCE(115);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'N') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'P') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'P') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'Q') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 'S') ADVANCE(113);
      END_STATE();
    case 28:
      if (lookahead == 'S') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'T') ADVANCE(101);
      END_STATE();
    case 30:
      if (lookahead == 'T') ADVANCE(19);
      END_STATE();
    case 31:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 'T') ADVANCE(105);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(103);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 35:
      if (lookahead == '{') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == '}') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      if (lookahead == '}') ADVANCE(122);
      END_STATE();
    case 38:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(127);
      END_STATE();
    case 39:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 40:
      if (eof) ADVANCE(42);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') SKIP(40);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '@') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 41:
      if (eof) ADVANCE(42);
      if (lookahead == '\n') ADVANCE(43);
      if (lookahead == '\r') SKIP(41);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '@') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\r') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\r') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(98);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_variable_declaration_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(90);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(43);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(62);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(75);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(82);
      if (lookahead == 'O') ADVANCE(79);
      if (lookahead == 'U') ADVANCE(83);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'C') ADVANCE(69);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(112);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(72);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(80);
      if (lookahead == 'R') ADVANCE(59);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(110);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(58);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(85);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H') ADVANCE(77);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H') ADVANCE(108);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I') ADVANCE(74);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(116);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(67);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N') ADVANCE(78);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(73);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(68);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(81);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Q') ADVANCE(71);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(114);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(84);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(102);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(70);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(61);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(106);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(104);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(65);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_variable_value);
      if (lookahead == '\r') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_variable_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_variable_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_request_separator);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '{') ADVANCE(93);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(98);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '{') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(98);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '}') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '}') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '}') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_request_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_request_line_token1);
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == '#') ADVANCE(127);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_request_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_GET);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_GET);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_POST);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_POST);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_PUT);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_PUT);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_PATCH);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_PATCH);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_DELETE);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_DELETE);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_HEAD);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_HEAD);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_GRAPHQL);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_GRAPHQL);
      if (lookahead == '.' ||
          lookahead == '_') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '{') ADVANCE(118);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(121);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '}') ADVANCE(121);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(120);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '}') ADVANCE(121);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(121);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '}') ADVANCE(119);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_interpolation);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_body);
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == '\r') ADVANCE(125);
      if (lookahead == '#') ADVANCE(127);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_body);
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_body);
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == '#') ADVANCE(127);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 41},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 40},
  [8] = {.lex_state = 40},
  [9] = {.lex_state = 40},
  [10] = {.lex_state = 40},
  [11] = {.lex_state = 40},
  [12] = {.lex_state = 40},
  [13] = {.lex_state = 40},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 41},
  [17] = {.lex_state = 41},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 41},
  [20] = {.lex_state = 41},
  [21] = {.lex_state = 50},
  [22] = {.lex_state = 41},
  [23] = {.lex_state = 41},
  [24] = {.lex_state = 41},
  [25] = {.lex_state = 41},
  [26] = {.lex_state = 41},
  [27] = {.lex_state = 41},
  [28] = {.lex_state = 41},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 53},
  [37] = {.lex_state = 51},
  [38] = {.lex_state = 51},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 41},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 88},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 88},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_request_separator] = ACTIONS(1),
    [aux_sym_request_line_token1] = ACTIONS(3),
    [anon_sym_GET] = ACTIONS(1),
    [anon_sym_POST] = ACTIONS(1),
    [anon_sym_PUT] = ACTIONS(1),
    [anon_sym_PATCH] = ACTIONS(1),
    [anon_sym_DELETE] = ACTIONS(1),
    [anon_sym_HEAD] = ACTIONS(1),
    [anon_sym_OPTIONS] = ACTIONS(1),
    [anon_sym_GRAPHQL] = ACTIONS(1),
    [sym_interpolation] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(59),
    [sym_variable_declaration] = STATE(16),
    [sym_request] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_blank_line] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [sym_request_separator] = ACTIONS(13),
    [aux_sym_request_line_token1] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_request_repeat1,
    STATE(61), 1,
      sym_request_line,
    STATE(65), 1,
      sym_method,
    ACTIONS(15), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [27] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(5), 1,
      aux_sym_request_repeat1,
    STATE(47), 1,
      sym_request_line,
    STATE(65), 1,
      sym_method,
    ACTIONS(19), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [54] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(2), 1,
      aux_sym_request_repeat1,
    STATE(46), 1,
      sym_request_line,
    STATE(65), 1,
      sym_method,
    ACTIONS(21), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [81] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_request_repeat1,
    STATE(43), 1,
      sym_request_line,
    STATE(65), 1,
      sym_method,
    ACTIONS(15), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [108] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(6), 1,
      aux_sym_request_repeat1,
    ACTIONS(23), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(26), 8,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_PATCH,
      anon_sym_DELETE,
      anon_sym_HEAD,
      anon_sym_OPTIONS,
      anon_sym_GRAPHQL,
  [129] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(32), 1,
      anon_sym_LF,
    ACTIONS(34), 1,
      sym_header_name,
    STATE(9), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(30), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(28), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [154] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(34), 1,
      sym_header_name,
    ACTIONS(40), 1,
      anon_sym_LF,
    STATE(12), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(38), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(36), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [179] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(34), 1,
      sym_header_name,
    ACTIONS(40), 1,
      anon_sym_LF,
    STATE(10), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(38), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(36), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [204] = 6,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(46), 1,
      sym_header_name,
    STATE(10), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(42), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
    ACTIONS(44), 3,
      sym_blank_line,
      sym_comment,
      anon_sym_LF,
  [227] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(34), 1,
      sym_header_name,
    ACTIONS(53), 1,
      anon_sym_LF,
    STATE(13), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(51), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [252] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(34), 1,
      sym_header_name,
    ACTIONS(59), 1,
      anon_sym_LF,
    STATE(10), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(57), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [277] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(34), 1,
      sym_header_name,
    ACTIONS(65), 1,
      anon_sym_LF,
    STATE(10), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(63), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [302] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(34), 1,
      sym_header_name,
    ACTIONS(65), 1,
      anon_sym_LF,
    STATE(15), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(63), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [327] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(34), 1,
      sym_header_name,
    ACTIONS(71), 1,
      anon_sym_LF,
    STATE(10), 1,
      aux_sym_request_repeat2,
    STATE(53), 1,
      sym_header,
    ACTIONS(69), 2,
      sym_blank_line,
      sym_comment,
    ACTIONS(67), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
  [352] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_request_separator,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      sym_blank_line,
    ACTIONS(77), 1,
      sym_comment,
    STATE(17), 3,
      sym_variable_declaration,
      sym_request,
      aux_sym_source_file_repeat1,
  [376] = 7,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym_blank_line,
    ACTIONS(84), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_AT,
    ACTIONS(90), 1,
      sym_request_separator,
    STATE(17), 3,
      sym_variable_declaration,
      sym_request,
      aux_sym_source_file_repeat1,
  [400] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(44), 3,
      sym_blank_line,
      sym_comment,
      anon_sym_LF,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_request_separator,
      sym_header_name,
  [415] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(95), 1,
      sym_comment,
    ACTIONS(93), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [428] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(99), 1,
      sym_comment,
    ACTIONS(97), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [441] = 5,
    ACTIONS(101), 1,
      aux_sym_variable_declaration_token1,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    STATE(33), 1,
      aux_sym_header_value_repeat1,
    STATE(51), 1,
      sym_header_value,
    ACTIONS(103), 2,
      aux_sym_request_name_token1,
      sym_interpolation,
  [458] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(109), 1,
      sym_comment,
    ACTIONS(107), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [471] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(113), 1,
      sym_comment,
    ACTIONS(111), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [484] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [497] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(121), 1,
      sym_comment,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [510] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(125), 1,
      sym_comment,
    ACTIONS(123), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [523] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(129), 1,
      sym_comment,
    ACTIONS(127), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [536] = 3,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(131), 4,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_AT,
      sym_request_separator,
  [549] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(135), 1,
      anon_sym_LF,
    STATE(29), 1,
      aux_sym_url_repeat1,
    ACTIONS(137), 2,
      aux_sym_url_token1,
      sym_interpolation,
  [563] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    STATE(31), 1,
      aux_sym_url_repeat1,
    STATE(57), 1,
      sym_url,
    ACTIONS(140), 2,
      aux_sym_url_token1,
      sym_interpolation,
  [577] = 4,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(142), 1,
      anon_sym_LF,
    STATE(29), 1,
      aux_sym_url_repeat1,
    ACTIONS(144), 2,
      aux_sym_url_token1,
      sym_interpolation,
  [591] = 5,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(146), 1,
      anon_sym_LF,
    ACTIONS(148), 1,
      aux_sym_request_name_token1,
    ACTIONS(151), 1,
      sym_interpolation,
    STATE(32), 1,
      aux_sym_header_value_repeat1,
  [607] = 5,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(154), 1,
      anon_sym_LF,
    ACTIONS(156), 1,
      aux_sym_request_name_token1,
    ACTIONS(158), 1,
      sym_interpolation,
    STATE(32), 1,
      aux_sym_header_value_repeat1,
  [623] = 5,
    ACTIONS(103), 1,
      sym_interpolation,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(160), 1,
      aux_sym_request_name_token1,
    STATE(33), 1,
      aux_sym_header_value_repeat1,
    STATE(39), 1,
      sym_header_value,
  [639] = 4,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(162), 1,
      anon_sym_LF,
    ACTIONS(164), 1,
      aux_sym_request_name_token1,
    STATE(58), 1,
      sym_request_name,
  [652] = 3,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(166), 1,
      aux_sym_variable_declaration_token1,
    ACTIONS(168), 1,
      anon_sym_EQ,
  [662] = 3,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(170), 1,
      aux_sym_variable_declaration_token1,
    ACTIONS(172), 1,
      sym_variable_value,
  [672] = 3,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(174), 1,
      aux_sym_variable_declaration_token1,
    ACTIONS(176), 1,
      sym_variable_value,
  [682] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(178), 1,
      anon_sym_LF,
  [689] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(180), 1,
      anon_sym_LF,
  [696] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(182), 1,
      anon_sym_EQ,
  [703] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(184), 1,
      sym_identifier,
  [710] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(186), 1,
      anon_sym_LF,
  [717] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(188), 1,
      sym_body,
  [724] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(190), 1,
      sym_variable_value,
  [731] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(192), 1,
      anon_sym_LF,
  [738] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(194), 1,
      anon_sym_LF,
  [745] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(196), 1,
      sym_body,
  [752] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(198), 1,
      anon_sym_LF,
  [759] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(200), 1,
      sym_body,
  [766] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(202), 1,
      anon_sym_LF,
  [773] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(204), 1,
      anon_sym_COLON,
  [780] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(206), 1,
      anon_sym_LF,
  [787] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(208), 1,
      sym_body,
  [794] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [801] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(212), 1,
      sym_body,
  [808] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(214), 1,
      anon_sym_LF,
  [815] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(216), 1,
      anon_sym_LF,
  [822] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
  [829] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(220), 1,
      sym_variable_value,
  [836] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(222), 1,
      anon_sym_LF,
  [843] = 2,
    ACTIONS(105), 1,
      aux_sym_request_line_token1,
    ACTIONS(224), 1,
      sym_body,
  [850] = 2,
    ACTIONS(3), 1,
      aux_sym_request_line_token1,
    ACTIONS(226), 1,
      anon_sym_LF,
  [857] = 1,
    ACTIONS(228), 1,
      aux_sym_request_line_token1,
  [861] = 1,
    ACTIONS(230), 1,
      aux_sym_request_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 129,
  [SMALL_STATE(8)] = 154,
  [SMALL_STATE(9)] = 179,
  [SMALL_STATE(10)] = 204,
  [SMALL_STATE(11)] = 227,
  [SMALL_STATE(12)] = 252,
  [SMALL_STATE(13)] = 277,
  [SMALL_STATE(14)] = 302,
  [SMALL_STATE(15)] = 327,
  [SMALL_STATE(16)] = 352,
  [SMALL_STATE(17)] = 376,
  [SMALL_STATE(18)] = 400,
  [SMALL_STATE(19)] = 415,
  [SMALL_STATE(20)] = 428,
  [SMALL_STATE(21)] = 441,
  [SMALL_STATE(22)] = 458,
  [SMALL_STATE(23)] = 471,
  [SMALL_STATE(24)] = 484,
  [SMALL_STATE(25)] = 497,
  [SMALL_STATE(26)] = 510,
  [SMALL_STATE(27)] = 523,
  [SMALL_STATE(28)] = 536,
  [SMALL_STATE(29)] = 549,
  [SMALL_STATE(30)] = 563,
  [SMALL_STATE(31)] = 577,
  [SMALL_STATE(32)] = 591,
  [SMALL_STATE(33)] = 607,
  [SMALL_STATE(34)] = 623,
  [SMALL_STATE(35)] = 639,
  [SMALL_STATE(36)] = 652,
  [SMALL_STATE(37)] = 662,
  [SMALL_STATE(38)] = 672,
  [SMALL_STATE(39)] = 682,
  [SMALL_STATE(40)] = 689,
  [SMALL_STATE(41)] = 696,
  [SMALL_STATE(42)] = 703,
  [SMALL_STATE(43)] = 710,
  [SMALL_STATE(44)] = 717,
  [SMALL_STATE(45)] = 724,
  [SMALL_STATE(46)] = 731,
  [SMALL_STATE(47)] = 738,
  [SMALL_STATE(48)] = 745,
  [SMALL_STATE(49)] = 752,
  [SMALL_STATE(50)] = 759,
  [SMALL_STATE(51)] = 766,
  [SMALL_STATE(52)] = 773,
  [SMALL_STATE(53)] = 780,
  [SMALL_STATE(54)] = 787,
  [SMALL_STATE(55)] = 794,
  [SMALL_STATE(56)] = 801,
  [SMALL_STATE(57)] = 808,
  [SMALL_STATE(58)] = 815,
  [SMALL_STATE(59)] = 822,
  [SMALL_STATE(60)] = 829,
  [SMALL_STATE(61)] = 836,
  [SMALL_STATE(62)] = 843,
  [SMALL_STATE(63)] = 850,
  [SMALL_STATE(64)] = 857,
  [SMALL_STATE(65)] = 861,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_request_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_request_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 4, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 4, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 5, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 5, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_request_repeat2, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_request_repeat2, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_request_repeat2, 2, 0, 0), SHIFT_REPEAT(52),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 5, 0, 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 5, 0, 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 6, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 6, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 6, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 6, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 7, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 7, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 7, 0, 6),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 7, 0, 6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 7, 0, 9),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 7, 0, 9),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 8, 0, 11),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 8, 0, 11),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 7, 0, 8),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 7, 0, 8),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 8, 0, 12),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 8, 0, 12),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 6, 0, 4),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 6, 0, 4),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 6, 0, 5),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 6, 0, 5),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 9, 0, 13),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 9, 0, 13),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_value, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 10),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 7),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_name, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 3, 0, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [218] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_http_request(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
